// Normalized catalog model for the "Все позиции" audit page.
// Real data comes from src/data/catalog.fixture.json (generated by
// scripts/import-catalog-fixture.mjs); falls back to the hand-written mock
// dishes so the app builds without the fixture.

import { categories, dishes } from "./mock-data";
import { readCatalogDataScenario, type CatalogDataScenario } from "@/lib/catalog-data-scenarios";

export type CatalogSection = {
  id: string;
  parentId: string | null;
  name: string;
  nameTranslations?: CatalogTranslations;
  imageUrl: string | null;
  sortOrder: number;
};

export type CatalogSectionNode = CatalogSection & { children: CatalogSectionNode[] };

export type CatalogLanguageCode = "ru" | "kk" | "en" | "sr";
export type CatalogTranslations = Partial<Record<CatalogLanguageCode, string>>;

export type CatalogNutrition = {
  calories: string;
  protein: string;
  fat: string;
  carbs: string;
};

export type CatalogOptionVariant = {
  id: string;
  name: string;
  price: string;
};

export type CatalogOptionGroup = {
  id: string;
  name: string;
  expanded: boolean;
  required: boolean;
  selection: "single" | "multiple";
  pricing: "total" | "surcharge";
  variants: CatalogOptionVariant[];
};

export type CatalogScheduleDay =
  | { mode: "allDay" }
  | { mode: "unavailable" }
  | { mode: "custom"; timeRange: { start: string; end: string } };

export type CatalogScheduleDayKey = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
export type CatalogWeeklySchedule = Record<CatalogScheduleDayKey, CatalogScheduleDay>;
export type CatalogAvailabilityScheduleMode = "available" | "unavailable";

export type CatalogLocalizedValue = {
  ru: string;
  kk?: string;
  en?: string;
  sr?: string;
};

export type CatalogRecommendationSource = "manual" | "automatic";

export type CatalogItemUpsell = {
  recommendationIds?: string[];
  recommendationSources?: Record<string, CatalogRecommendationSource>;
  sticker?: CatalogLocalizedValue | null;
  tags?: CatalogLocalizedValue[];
  keywords?: CatalogLocalizedValue[];
};

/** Rebuild the section hierarchy from flat parentId links. */
export function buildSectionTree(sections: CatalogSection[]): CatalogSectionNode[] {
  const nodes = new Map(sections.map((s) => [s.id, { ...s, children: [] as CatalogSectionNode[] }]));
  const roots: CatalogSectionNode[] = [];
  for (const node of nodes.values()) {
    const parent = node.parentId ? nodes.get(node.parentId) : undefined;
    (parent ? parent.children : roots).push(node);
  }
  return roots;
}

export type CatalogItem = {
  id: string;
  title: string;
  sectionId: string;
  sectionName: string;
  thumbnailUrl: string | null;
  price: number;
  priceWithSale: number | null;
  status: "active" | "stopped" | "archive" | "coming-soon";
  scheduled: boolean;
  guestLabels: string[];
  tags: string[];
  /** Canonical references to the shared catalog label directory. */
  tagIds?: string[];
  stickerId?: string | null;
  optionsCount: number;
  modifiersCount: number;
  recommendationsCount: number;
  /** Guest-facing display: full card, no order button, or no button and no price. */
  displayMode: "full" | "no-button" | "no-price";
  /** Base-language (ru) description text; empty string when unset. */
  description: string;
  hasDescription: boolean;
  weightLabel: string | null;
  /** Filled nutrition fields out of 4 (kcal, fat, protein, carbs). */
  nutritionFilledCount: number;
  /** Fully translated extra languages out of translationTotalCount. */
  translationFilledCount: number;
  translationTotalCount: number;
  hasDiscount: boolean;
  /** Canonical editor values restored with the item record. */
  titleTranslations?: CatalogTranslations;
  nutrition?: CatalogNutrition;
  optionGroups?: CatalogOptionGroup[];
  unavailableDisplayMode?: "hidden" | "comingSoon";
  outsideScheduleMode?: "hidden" | "comingSoon";
  weeklySchedule?: CatalogWeeklySchedule;
  availabilityScheduleMode?: CatalogAvailabilityScheduleMode;
  /** Availability mode to restore after an archived item is returned to the menu. */
  archivedAvailabilityMode?: "always" | "unavailable" | "schedule";
  upsell?: CatalogItemUpsell;
};

type CatalogFixture = {
  generatedAt: string;
  menuName: string;
  sections: CatalogSection[];
  items: CatalogItem[];
};

const fixtureModules = import.meta.glob<{ default: CatalogFixture }>("./catalog.fixture.json", {
  eager: true,
});
const fixture = Object.values(fixtureModules)[0]?.default ?? null;

// ponytail: minimal conversion of the 7 mock dishes; no thumbnails or audit variety
function fallbackFixture(): CatalogFixture {
  const sections: CatalogSection[] = categories.map((c, i) => ({
    id: c.id,
    parentId: null,
    name: c.name,
    imageUrl: null,
    sortOrder: i,
  }));
  const sectionByName = new Map(sections.map((s) => [s.name, s]));
  const items: CatalogItem[] = dishes.map((d) => {
    const section = sectionByName.get(d.category);
    return {
      id: d.id,
      title: d.name,
      description: d.description,
      sectionId: section?.id ?? "no-section",
      sectionName: section?.name ?? "Без раздела",
      thumbnailUrl: null,
      price: Number(d.price.replace(/[^\d]/g, "")) || 0,
      priceWithSale: null,
      status: d.stop ? "stopped" : "active",
      scheduled: false,
      guestLabels: [],
      tags: [],
      optionsCount: 0,
      modifiersCount: 0,
      recommendationsCount: d.recommendations.length,
      displayMode: "full",
      hasDescription: Boolean(d.description.trim()),
      weightLabel: d.weight || null,
      nutritionFilledCount: 0,
      translationFilledCount: 0,
      translationTotalCount: 2,
      hasDiscount: false,
    };
  });
  return { generatedAt: "", menuName: "Mock", sections, items };
}

const data = fixture ?? fallbackFixture();

const DEMO_SECTIONS: CatalogSection[] = [
  { id: "demo-kitchen", parentId: null, name: "Кухня", imageUrl: null, sortOrder: 0 },
  { id: "demo-breakfast", parentId: "demo-kitchen", name: "Завтраки", imageUrl: null, sortOrder: 0 },
  { id: "demo-drinks", parentId: null, name: "Напитки", imageUrl: null, sortOrder: 1 },
];

function demoItem(
  id: string,
  title: string,
  section: CatalogSection,
  price: number,
  patch: Partial<CatalogItem> = {},
): CatalogItem {
  return {
    id,
    title,
    sectionId: section.id,
    sectionName: section.name,
    thumbnailUrl: null,
    price,
    priceWithSale: null,
    status: "active",
    scheduled: false,
    guestLabels: [],
    tags: [],
    optionsCount: 0,
    modifiersCount: 0,
    recommendationsCount: 0,
    displayMode: "full",
    description: "",
    hasDescription: false,
    weightLabel: null,
    nutritionFilledCount: 0,
    translationFilledCount: 0,
    translationTotalCount: 2,
    hasDiscount: false,
    ...patch,
  };
}

const demoBreakfast = DEMO_SECTIONS[1];
const demoDrinks = DEMO_SECTIONS[2];
const DEMO_ITEMS: CatalogItem[] = [
  demoItem("demo-omelet", "Омлет с томатами", demoBreakfast, 2400, { description: "Яйца, томаты и сыр", hasDescription: true, weightLabel: "280 г" }),
  demoItem("demo-pancakes", "Панкейки", demoBreakfast, 2100, { description: "С ягодами и кремом", hasDescription: true }),
  demoItem("demo-croissant", "Круассан", demoBreakfast, 1200),
  demoItem("demo-porridge", "Овсяная каша", demoBreakfast, 1600, { weightLabel: "300 г" }),
  demoItem("demo-coffee", "Капучино", demoDrinks, 1100, { weightLabel: "300 мл" }),
  demoItem("demo-tea", "Чай с облепихой", demoDrinks, 1400, { description: "Облепиха, мёд и апельсин", hasDescription: true }),
  demoItem("demo-water", "Вода", demoDrinks, 600),
];

export function getCatalogSeedForScenario(scenario: CatalogDataScenario): Pick<CatalogFixture, "sections" | "items"> {
  if (scenario === "empty") return { sections: [], items: [] };
  if (scenario === "demo") return { sections: DEMO_SECTIONS, items: DEMO_ITEMS };
  return { sections: data.sections, items: data.items };
}

const activeSeed = getCatalogSeedForScenario(readCatalogDataScenario());

export const catalogSections: CatalogSection[] = activeSeed.sections;
export const catalogItems: CatalogItem[] = activeSeed.items;

export function formatPrice(value: number) {
  return `${value.toLocaleString("ru-RU")} ₸`;
}
