// Normalized catalog model for the "Все позиции" audit page.
// Real data comes from src/data/catalog.fixture.json (generated by
// scripts/import-catalog-fixture.mjs); falls back to the hand-written mock
// dishes so the app builds without the fixture.

import { categories, dishes } from "./mock-data";

export type CatalogSection = {
  id: string;
  parentId: string | null;
  name: string;
  imageUrl: string | null;
  sortOrder: number;
};

export type CatalogSectionNode = CatalogSection & { children: CatalogSectionNode[] };

/** Rebuild the section hierarchy from flat parentId links. */
export function buildSectionTree(sections: CatalogSection[]): CatalogSectionNode[] {
  const nodes = new Map(sections.map((s) => [s.id, { ...s, children: [] as CatalogSectionNode[] }]));
  const roots: CatalogSectionNode[] = [];
  for (const node of nodes.values()) {
    const parent = node.parentId ? nodes.get(node.parentId) : undefined;
    (parent ? parent.children : roots).push(node);
  }
  return roots;
}

export type CatalogItem = {
  id: string;
  title: string;
  sectionId: string;
  sectionName: string;
  thumbnailUrl: string | null;
  price: number;
  priceWithSale: number | null;
  status: "active" | "stopped" | "archive" | "coming-soon";
  scheduled: boolean;
  guestLabels: string[];
  tags: string[];
  optionsCount: number;
  modifiersCount: number;
  recommendationsCount: number;
  /** Guest-facing display: full card, no order button, or no button and no price. */
  displayMode: "full" | "no-button" | "no-price";
  /** Base-language (ru) description text; empty string when unset. */
  description: string;
  hasDescription: boolean;
  weightLabel: string | null;
  /** Filled nutrition fields out of 4 (kcal, fat, protein, carbs). */
  nutritionFilledCount: number;
  /** Fully translated extra languages out of translationTotalCount. */
  translationFilledCount: number;
  translationTotalCount: number;
  hasDiscount: boolean;
};

type CatalogFixture = {
  generatedAt: string;
  menuName: string;
  sections: CatalogSection[];
  items: CatalogItem[];
};

const fixtureModules = import.meta.glob<{ default: CatalogFixture }>("./catalog.fixture.json", {
  eager: true,
});
const fixture = Object.values(fixtureModules)[0]?.default ?? null;

// ponytail: minimal conversion of the 7 mock dishes; no thumbnails or audit variety
function fallbackFixture(): CatalogFixture {
  const sections: CatalogSection[] = categories.map((c, i) => ({
    id: c.id,
    parentId: null,
    name: c.name,
    imageUrl: null,
    sortOrder: i,
  }));
  const sectionByName = new Map(sections.map((s) => [s.name, s]));
  const items: CatalogItem[] = dishes.map((d) => {
    const section = sectionByName.get(d.category);
    return {
      id: d.id,
      title: d.name,
      description: d.description,
      sectionId: section?.id ?? "no-section",
      sectionName: section?.name ?? "Без раздела",
      thumbnailUrl: null,
      price: Number(d.price.replace(/[^\d]/g, "")) || 0,
      priceWithSale: null,
      status: d.stop ? "stopped" : "active",
      scheduled: false,
      guestLabels: [],
      tags: [],
      optionsCount: 0,
      modifiersCount: 0,
      recommendationsCount: d.recommendations.length,
      displayMode: "full",
      hasDescription: Boolean(d.description.trim()),
      weightLabel: d.weight || null,
      nutritionFilledCount: 0,
      translationFilledCount: 0,
      translationTotalCount: 2,
      hasDiscount: false,
    };
  });
  return { generatedAt: "", menuName: "Mock", sections, items };
}

const data = fixture ?? fallbackFixture();

export const catalogSections: CatalogSection[] = data.sections;
export const catalogItems: CatalogItem[] = data.items;

export function formatPrice(value: number) {
  return `${value.toLocaleString("ru-RU")} ₸`;
}
